/* PDFStar – Translations (25 languages) */
window.PDFStar_LANGS = {
    tr: { name: 'Türkçe', dir: 'ltr', flag: '🇹🇷' },
    en: { name: 'English', dir: 'ltr', flag: '🇬🇧' },
    es: { name: 'Español', dir: 'ltr', flag: '🇪🇸' },
    fr: { name: 'Français', dir: 'ltr', flag: '🇫🇷' },
    de: { name: 'Deutsch', dir: 'ltr', flag: '🇩🇪' },
    it: { name: 'Italiano', dir: 'ltr', flag: '🇮🇹' },
    pt: { name: 'Português', dir: 'ltr', flag: '🇧🇷' },
    ja: { name: '日本語', dir: 'ltr', flag: '🇯🇵' },
    ru: { name: 'Русский', dir: 'ltr', flag: '🇷🇺' },
    ko: { name: '한국어', dir: 'ltr', flag: '🇰🇷' },
    zh: { name: '中文(简体)', dir: 'ltr', flag: '🇨🇳' },
    zt: { name: '中文(繁體)', dir: 'ltr', flag: '🇹🇼' },
    ar: { name: 'العربية', dir: 'rtl', flag: '🇸🇦' },
    bg: { name: 'Български', dir: 'ltr', flag: '🇧🇬' },
    ca: { name: 'Català', dir: 'ltr', flag: '🏴' },
    nl: { name: 'Nederlands', dir: 'ltr', flag: '🇳🇱' },
    el: { name: 'Ελληνικά', dir: 'ltr', flag: '🇬🇷' },
    hi: { name: 'हिन्दी', dir: 'ltr', flag: '🇮🇳' },
    id: { name: 'Bahasa Indonesia', dir: 'ltr', flag: '🇮🇩' },
    ms: { name: 'Bahasa Melayu', dir: 'ltr', flag: '🇲🇾' },
    pl: { name: 'Polski', dir: 'ltr', flag: '🇵🇱' },
    sv: { name: 'Svenska', dir: 'ltr', flag: '🇸🇪' },
    th: { name: 'ภาษาไทย', dir: 'ltr', flag: '🇹🇭' },
    uk: { name: 'Українська', dir: 'ltr', flag: '🇺🇦' },
    vi: { name: 'Tiếng Việt', dir: 'ltr', flag: '🇻🇳' },
};

window.T = {
    // nav
    'nav-tools': { tr: 'Araçlar', en: 'Tools', es: 'Herramientas', fr: 'Outils', de: 'Werkzeuge', it: 'Strumenti', pt: 'Ferramentas', ja: 'ツール', ru: 'Инструменты', ko: '도구', zh: '工具', zt: '工具', ar: 'الأدوات', bg: 'Инструменти', ca: 'Eines', nl: 'Hulpmiddelen', el: 'Εργαλεία', hi: 'उपकरण', id: 'Alat', ms: 'Alat', pl: 'Narzędzia', sv: 'Verktyg', th: 'เครื่องมือ', uk: 'Інструменти', vi: 'Công cụ' },
    'nav-features': { tr: 'Özellikler', en: 'Features', es: 'Características', fr: 'Fonctionnalités', de: 'Funktionen', it: 'Caratteristiche', pt: 'Recursos', ja: '機能', ru: 'Возможности', ko: '기능', zh: '功能', zt: '功能', ar: 'المميزات', bg: 'Функции', ca: 'Funcions', nl: 'Functies', el: 'Χαρακτηριστικά', hi: 'विशेषताएँ', id: 'Fitur', ms: 'Ciri', pl: 'Funkcje', sv: 'Funktioner', th: 'คุณสมบัติ', uk: 'Функції', vi: 'Tính năng' },
    'nav-faq': { tr: 'SSS', en: 'FAQ', es: 'Preguntas', fr: 'FAQ', de: 'FAQ', it: 'FAQ', pt: 'FAQ', ja: 'よくある質問', ru: 'FAQ', ko: '자주 묻는 질문', zh: '常见问题', zt: '常見問題', ar: 'الأسئلة', bg: 'ЧЗВ', ca: 'FAQ', nl: 'FAQ', el: 'Συχνές ερωτήσεις', hi: 'सामान्य प्रश्न', id: 'FAQ', ms: 'Soalan Lazim', pl: 'FAQ', sv: 'Vanliga frågor', th: 'คำถามที่พบบ่อย', uk: 'Питання', vi: 'Câu hỏi' },
    'nav-cta': { tr: 'Hemen Başla', en: 'Get Started', es: 'Comenzar', fr: 'Commencer', de: 'Loslegen', it: 'Inizia', pt: 'Começar', ja: '始める', ru: 'Начать', ko: '시작하기', zh: '立即开始', zt: '立即開始', ar: 'ابدأ الآن', bg: 'Започнете', ca: 'Comença', nl: 'Aan de slag', el: 'Ξεκινήστε', hi: 'शुरू करें', id: 'Mulai', ms: 'Mulakan', pl: 'Zacznij', sv: 'Kom igång', th: 'เริ่มต้น', uk: 'Розпочати', vi: 'Bắt đầu' },
    // hero
    'hero-badge': { tr: '%100 Ücretsiz & Güvenli', en: '100% Free & Secure', es: '100% Gratis y Seguro', fr: '100% Gratuit & Sécurisé', de: '100% Kostenlos & Sicher', it: '100% Gratuito e Sicuro', pt: '100% Grátis e Seguro', ja: '100%無料・安全', ru: '100% Бесплатно', ko: '100% 무료 & 안전', zh: '100% 免费安全', zt: '100% 免費安全', ar: 'مجاني 100% وآمن', bg: '100% Безплатно', ca: '100% Gratuït i Segur', nl: '100% Gratis & Veilig', el: '100% Δωρεάν & Ασφαλές', hi: '100% निःशुल्क', id: '100% Gratis & Aman', ms: '100% Percuma & Selamat', pl: '100% Darmowe', sv: '100% Gratis & Säkert', th: 'ฟรี 100%', uk: '100% Безкоштовно', vi: '100% Miễn phí' },
    'hero-title-1': { tr: 'PDF İşlemleri için', en: 'For PDF Operations', es: 'Para Operaciones PDF', fr: 'Pour les opérations PDF', de: 'Für PDF-Operationen', it: 'Per Operazioni PDF', pt: 'Para Operações PDF', ja: 'PDF操作に', ru: 'Для работы с PDF', ko: 'PDF 작업을 위한', zh: '为PDF操作而生', zt: '為PDF操作而生', ar: 'لعمليات PDF', bg: 'За PDF операции', ca: 'Per a operacions PDF', nl: 'Voor PDF-bewerkingen', el: 'Για λειτουργίες PDF', hi: 'PDF ऑपरेशन्स के लिए', id: 'Untuk Operasi PDF', ms: 'Untuk Operasi PDF', pl: 'Dla operacji PDF', sv: 'För PDF-operationer', th: 'สำหรับการจัดการ PDF', uk: 'Для роботи з PDF', vi: 'Cho các thao tác PDF' },
    'hero-title-2': { tr: 'Güçlü Araçlar', en: 'Powerful Tools', es: 'Herramientas Potentes', fr: 'Outils Puissants', de: 'Leistungsstarke Werkzeuge', it: 'Strumenti Potenti', pt: 'Ferramentas Poderosas', ja: '強力なツール', ru: 'Мощные инструменты', ko: '강력한 도구', zh: '强大的工具', zt: '強大的工具', ar: 'أدوات قوية', bg: 'Мощни инструменти', ca: 'Eines Potents', nl: 'Krachtige tools', el: 'Ισχυρά Εργαλεία', hi: 'शक्तिशाली उपकरण', id: 'Alat Kuat', ms: 'Alat Hebat', pl: 'Potężne narzędzia', sv: 'Kraftfulla verktyg', th: 'เครื่องมือทรงพลัง', uk: 'Потужні інструменти', vi: 'Công cụ Mạnh mẽ' },
    'hero-desc': { tr: 'Birleştir, böl, sıkıştır, dönüştür — tüm PDF işlemleriniz<br />tek bir yerde. Kayıt gerekmez.', en: 'Merge, split, compress, convert — all your PDF operations<br />in one place. No signup required.', es: 'Combinar, dividir, comprimir, convertir — todas sus operaciones PDF<br />en un solo lugar. No requiere registro.', fr: 'Fusionner, diviser, compresser, convertir — toutes vos opérations PDF<br />au même endroit. Aucune inscription requise.', de: 'Zusammenführen, teilen, komprimieren, konvertieren — alle Ihre PDF-Vorgänge<br />an einem Ort. Keine Anmeldung erforderlich.', it: 'Unisci, dividi, comprimi, converti — tutte le tue operazioni PDF<br />in un unico posto. Nessuna registrazione.', pt: 'Mesclar, dividir, comprimir, converter — todas as suas operações de PDF<br />em um só lugar. Sem registro.', ja: '結合、分割、圧縮、変換 — すべてのPDF操作を<br />1か所で。登録不要。', ru: 'Плюс, разделяйте, сжимайте, конвертируйте — все ваши операции с PDF<br />в одном месте. Регистрация не нужна.', ko: 'PDF 병합, 분할, 압축, 변환 — 모든 PDF 작업을<br />한 곳에서. 가입 불필요.', zh: '合并、拆分、压缩、转换——所有PDF操作<br />一站式解决。无需注册。', zt: '合併、拆分、壓縮、轉換——所有PDF操作<br />一站式解決。無需註冊。', ar: 'دمج، تقسيم، ضغط، تحويل — جميع عمليات PDF<br />في مكان واحد. لا يلزم التسجيل.', bg: 'Обединяване, разделяне, компресиране, конвертиране — всички ваши PDF операции<br />на едно място. Без регистрация.', ca: 'Unir, dividir, comprimir, convertir — totes les teves operacions PDF<br />en un sol lloc. Sense registre.', nl: 'Samenvoegen, splitsen, comprimeren, converteren — al uw PDF-bewerkingen<br />op één plek. Geen registratie vereist.', el: 'Συγχώνευση, διαχωρισμός, συμπίεση, μετατροπή — όλες οι λειτουργίες PDF<br />σε ένα μέρος. Δεν απαιτείται εγγραφή.', hi: 'मर्ज, स्प्लिट, कंप्रेस, कन्वर्ट — आपके सभी PDF कार्य<br />एक ही स्थान पर। कोई साइनअप नहीं।', id: 'Gabung, pisah, kompres, konversi — semua operasi PDF Anda<br />di satu tempat. Tanpa daftar.', ms: 'Gabung, pisah, mampat, tukar — semua operasi PDF anda<br />di satu tempat. Tanpa pendaftaran.', pl: 'Połącz, podziel, skompresuj, konwertuj — wszystkie operacje PDF<br />w jednym miejscu. Bez rejestracji.', sv: 'Slå ihop, dela, komprimera, konvertera — alla dina PDF-operationer<br />på ett ställe. Ingen registrering krävs.', th: 'รวม, แบ่ง, บีบอัด, แปลง — การจัดการ PDF ของคุณ<br />ในที่เดียว ไม่ต้องสมัครสมาชิก.', uk: 'Об\'єднуйте, розділяйте, стискайте, конвертуйте — усі ваші PDF-операції<br />в одному місці. Без реєстрації.', vi: 'Gộp, tách, nén, chuyển đổi — tất cả các thao tác PDF của bạn<br />tại một nơi. Không cần đăng ký.' },
    'hero-cta1': { tr: 'Araçları Keşfet', en: 'Explore Tools', es: 'Explorar', fr: 'Explorer', de: 'Entdecken', it: 'Esplora', pt: 'Explorar', ja: 'ツールを見る', ru: 'Инструменты', ko: '도구 보기', zh: '浏览工具', zt: '瀏覽工具', ar: 'استكشف الأدوات', bg: 'Разгледайте', ca: 'Exploreu', nl: 'Verkennen', el: 'Εξερευνήστε', hi: 'देखें', id: 'Jelajahi', ms: 'Terokai', pl: 'Przeglądaj', sv: 'Utforska', th: 'สำรวจ', uk: 'Переглянути', vi: 'Khám phá' },
    'hero-cta2': { tr: 'PDF Yükle', en: 'Upload PDF', es: 'Subir PDF', fr: 'Uploader PDF', de: 'PDF hochladen', it: 'Carica PDF', pt: 'Enviar PDF', ja: 'PDFをアップロード', ru: 'Получить PDF', ko: 'PDF 파일 업로드', zh: '上传PDF', zt: '上傳PDF', ar: 'تحميل PDF', bg: 'Качи PDF', ca: 'Pujar PDF', nl: 'PDF Uploaden', el: 'Μεταφόρτωση PDF', hi: 'PDF अपलोड करें', id: 'Unggah PDF', ms: 'Muat Naik PDF', pl: 'Prześlij PDF', sv: 'Ladda upp PDF', th: 'อัปโหลด PDF', uk: 'Завантажити PDF', vi: 'Tải PDF lên' },
    // features
    'features-badge': { tr: 'Neden PDFStar?', en: 'Why PDFStar?', es: '¿Por qué PDFStar?', fr: 'Pourquoi PDFStar?', de: 'Warum PDFStar?', it: 'Perché PDFStar?', pt: 'Por que PDFStar?', ja: 'なぜPDFStar？', ru: 'Почему PDFStar?', ko: '왜 PDFStar인가?', zh: '为什么选择PDFStar？', zt: '為什麼選擇PDFStar？', ar: 'لماذا PDFStar؟', bg: 'Защо PDFStar?', ca: 'Per què PDFStar?', nl: 'Waarom PDFStar?', el: 'Γιατί το PDFStar;', hi: 'PDFStar क्यों?', id: 'Mengapa PDFStar?', ms: 'Mengapa PDFStar?', pl: 'Dlaczego PDFStar?', sv: 'Varför PDFStar?', th: 'ทำไมต้อง PDFStar?', uk: 'Чому PDFStar?', vi: 'Vì sao chọn PDFStar?' },
    'features-title': { tr: 'Rekabetsiz Özellikler', en: 'Unbeatable Features', es: 'Características Inigualables', fr: 'Fonctionnalités Inégalées', de: 'Unschlagbare Funktionen', it: 'Funzionalità Imbattibili', pt: 'Recursos Imbatíveis', ja: '他にはない機能', ru: 'Непревзойденные функции', ko: '경쟁 없는 기능', zh: '无与伦比的功能', zt: '無與倫比的功能', ar: 'ميزات لا تضاهى', bg: 'Ненадминати функции', ca: 'Característiques Imbatibles', nl: 'Onverslaanbare Functies', el: 'Ασυναγώνιστα Χαρακτηριστικά', hi: 'अजेय विशेषताएँ', id: 'Fitur Tak Terkalahkan', ms: 'Ciri Tidak Tandingan', pl: 'Bezkonkurencyjne funkcje', sv: 'Oslagbara funktioner', th: 'คุณสมบัติที่ไม่มีใครเทียบ', uk: 'Неперевершені функції', vi: 'Tính năng vô song' },
    'feat-sec-title': { tr: 'Uçtan Uca Güvenlik', en: 'End-to-End Security', es: 'Seguridad de Extremo a Extremo', fr: 'Sécurité de Bout en Bout', de: 'End-to-End-Sicherheit', it: 'Sicurezza End-to-End', pt: 'Segurança de Ponta a Ponta', ja: 'エンドツーエンドのセキュリティ', ru: 'Сквозная безопасность', ko: '종단 간 보안', zh: '端到端安全', zt: '端到端安全', ar: 'أمان من البداية للنهاية', bg: 'Защита от край до край', ca: 'Seguretat d\'Extrem a Extrem', nl: 'End-to-end Beveiliging', el: 'Ασφάλεια από άκρο σε άκρο', hi: 'एंड-टू-एंड सुरक्षा', id: 'Keamanan End-to-End', ms: 'Keselamatan Hujung ke Hujung', pl: 'Zabezpieczenia od końca do końca', sv: 'End-to-end-säkerhet', th: 'ความปลอดภัยแบบครบวงจร', uk: 'Наскрізна безпека', vi: 'Bảo mật đầu cuối' },
    'feat-sec-desc': { tr: 'Dosyalarınız tarayıcınızda işlenir. Sunucuya yüklenme olmaz.', en: 'Files are processed in your browser. No server uploads.', es: 'Los archivos se procesan en su navegador. Sin cargas al servidor.', fr: 'Fichiers traités dans le navigateur. Aucun upload sur serveur.', de: 'Dateien werden im Browser verarbeitet. Keine Server-Uploads.', it: 'I file vengono elaborati nel browser. Nessun caricamento.', pt: 'Arquivos são processados no navegador. Sem uploads no servidor.', ja: 'ファイルはブラウザで処理されます。サーバーへのアップロードなし。', ru: 'Файлы обрабатываются в браузере. Без загрузки на сервер.', ko: '파일은 브라우저에서 처리됩니다. 서버 업로드 없음.', zh: '文件在浏览器中处理。无服务器上传。', zt: '檔案在瀏覽器中處理。無伺服器上傳。', ar: 'تتم معالجة الملفات في المتصفح. لا يتم رفعها للخادم.', bg: 'Файловете се обработват в браузъра. Без качване на сървър.', ca: 'Els fitxers es processen al navegador. Sense càrregues al servidor.', nl: 'Bestanden worden verwerkt in de browser. Geen server uploads.', el: 'Τα αρχεία επεξεργάζονται στο πρόγραμμα περιήγησης. Χωρίς μεταφορτώσεις σε διακομιστή.', hi: 'फ़ाइलें आपके ब्राउज़र में संसाधित होती हैं। कोई सर्वर अपलोड नहीं।', id: 'File diproses di browser Anda. Tanpa unggahan server.', ms: 'Fail diproses dalam pelayar web anda. Tiada muat naik pelayan.', pl: 'Pliki są przetwarzane w przeglądarce. Żadnych wysyłek na serwer.', sv: 'Filer bearbetas i din webbläsare. Inga serveruppladdningar.', th: 'ไฟล์ถูกประมวลผลในเบราว์เซอร์ของคุณ ไม่มีการอัปโหลดเซิร์ฟเวอร์', uk: 'Файли обробляються у вашому браузері. Без завантажень на сервер.', vi: 'Tệp được xử lý trong trình duyệt. Không tải lên máy chủ.' },
    'feat-fast-title': { tr: 'Yıldırım Hızı', en: 'Lightning Speed', es: 'Velocidad Relámpago', fr: 'Vitesse Éclair', de: 'Blitzschnell', it: 'Velocità della Luce', pt: 'Velocidade Relâmpago', ja: 'ライトニングスピード', ru: 'Молниеносная скорость', ko: '초고속', zh: '闪电速度', zt: '閃電速度', ar: 'سرعة البرق', bg: 'Светкавична скорост', ca: 'Velocitat Llamp', nl: 'Bliksemsnel', el: 'Αστραπιαία Ταχύτητα', hi: 'बिजली की गति', id: 'Kecepatan Kilat', ms: 'Kelajuan Kilat', pl: 'Błyskawiczna prędkość', sv: 'Blixtsnabb', th: 'ความเร็วปานสายฟ้า', uk: 'Блискавична швидкість', vi: 'Tốc độ chớp nhoáng' },
    'feat-fast-desc': { tr: 'WebAssembly ile güçlendirilmiş, saniyeler içinde sonuç alın.', en: 'Powered by WebAssembly, get results in seconds.', es: 'Impulsado por WebAssembly, resultados en segundos.', fr: 'Propulsé par WebAssembly, résultats en quelques secondes.', de: 'Angetrieben durch WebAssembly, Ergebnisse in Sekunden.', it: 'Potenziato da WebAssembly, ottieni risultati in pochi secondi.', pt: 'Por WebAssembly, obtenha resultados em segundos.', ja: 'WebAssemblyで数秒で結果を取得。', ru: 'На базе WebAssembly, результаты за секунды.', ko: 'WebAssembly 기반으로 몇 초 만에 결과 도출.', zh: '由WebAssembly驱动，秒出结果。', zt: '由WebAssembly驅動，秒出結果。', ar: 'مدعوم من WebAssembly، نتائج في ثوانٍ.', bg: 'Задвижвано от WebAssembly, резултати за секунди.', ca: 'Potenciat amb WebAssembly, resultats en segons.', nl: 'Met WebAssembly, resultaten in seconden.', el: 'Με WebAssembly, λάβετε αποτελέσματα σε δευτερόλεπτα.', hi: 'WebAssembly द्वारा संचालित, सेकंड में परिणाम।', id: 'Didukung oleh WebAssembly, dapatkan hasil dalam hitungan detik.', ms: 'Dikuasakan WebAssembly, hasil dalam beberapa saat.', pl: 'Z WebAssembly, uzyskaj wyniki w kilka sekund.', sv: 'Drivs av WebAssembly, få resultat på några sekunder.', th: 'เว็บแอสเซมบลี รับผลลัพธ์ในพริบตา', uk: 'Створено з WebAssembly, результати за секунди.', vi: 'Với WebAssembly, có kết quả trong vài giây.' },
    'feat-free-title': { tr: 'Tamamen Ücretsiz', en: 'Completely Free', es: 'Completamente Gratis', fr: 'Entièrement Gratuit', de: 'Völlig Kostenlos', it: 'Completamente Gratuito', pt: 'Totalmente Grátis', ja: '完全無料', ru: 'Полностью бесплатно', ko: '완전 무료', zh: '完全免费', zt: '完全免費', ar: 'مجاني تماماً', bg: 'Напълно безплатно', ca: 'Completament Gratuït', nl: 'Volledig Gratis', el: 'Εντελώς Δωρεάν', hi: 'पूरी तरह से मुफ़्त', id: 'Sepenuhnya Gratis', ms: 'Sepenuhnya Percuma', pl: 'Całkowicie za darmo', sv: 'Helt Gratis', th: 'ฟรีโดยสมบูรณ์', uk: 'Повністю безкоштовно', vi: 'Hoàn toàn Miễn phí' },
    'feat-free-desc': { tr: 'Sınırsız kullanım, kayıt yok, reklam yok. Gerçekten ücretsiz.', en: 'Unlimited use, no registration, no ads. Truly free.', es: 'Uso ilimitado, sin registro, sin publicidad. Realmente gratis.', fr: 'Utilisation illimitée, sans inscription, sans pub. Vraiment gratuit.', de: 'Unbegrenzte Nutzung, keine Anmeldung, keine Werbung. Kostenlos.', it: 'Uso illimitato, nessuna registrazione, nessuna pubblicità. Gratis.', pt: 'Uso ilimitado, sem registro, sem anúncios. Realmente grátis.', ja: '無制限利用、登録なし、広告なし。本当に無料。', ru: 'Безгранично, без регистрации, без рекламы. Действительно бесплатно.', ko: '무제한, 가입 없음, 광고 없음. 진정한 무료.', zh: '无限制使用，无注册，无广告。真正免费。', zt: '無限制使用，無註冊，無廣告。真正免費。', ar: 'استخدام غير محدود، لا تسجيل، لا إعلانات. مجاني حقاً.', bg: 'Неограничена употреба, без регистрация, без реклами.', ca: 'Ús il·limitat, sense registre ni anuncis. Realment gratuït.', nl: 'Onbeperkt, geen registratie, geen advertenties. Echt gratis.', el: 'Απεριόριστη χρήση, χωρίς εγγραφή, χωρίς διαφημίσεις.', hi: 'असीमित उपयोग, पंजीकरण नहीं, कोई विज्ञापन नहीं। सचमुच मुफ़्त।', id: 'Penggunaan tak terbatas, tanpa daftar, tanpa iklan. Benar-benar gratis.', ms: 'Penggunaan tanpa had, tiada pendaftaran, tiada iklan.', pl: 'Bez ograniczeń, bez rejestracji, bez reklam. Naprawdę darmowe.', sv: 'Obegränsat bruk, ingen registrering, inga annonser. Helt gratis.', th: 'ใช้งานไม่จำกัด ไม่มีการสมัคร ไม่มีโฆษณา ฟรีจริงๆ', uk: 'Без обмежень, без реєстрації, без реклами. Дійсно безкоштовно.', vi: 'Dùng vô hạn, không đăng ký, không quảng cáo. Thật sự miễn phí.' },
    'feat-quality-title': { tr: 'Yüksek Kalite', en: 'High Quality', es: 'Alta Calidad', fr: 'Haute Qualité', de: 'Hohe Qualität', it: 'Alta Qualità', pt: 'Alta Qualidade', ja: '高品質', ru: 'Высокое качество', ko: '고품질', zh: '高质量', zt: '高品質', ar: 'جودة عالية', bg: 'Високо качество', ca: 'Alta Qualitat', nl: 'Hoge Kwaliteit', el: 'Υψηλή Ποιότητα', hi: 'उच्च गुणवत्ता', id: 'Kualitas Tinggi', ms: 'Kualiti Tinggi', pl: 'Wysoka jakość', sv: 'Hög Kvalitet', th: 'คุณภาพสูง', uk: 'Висока якість', vi: 'Chất lượng cao' },
    'feat-quality-desc': { tr: 'İşlemler sonrası orijinal kalite korunur, piksel yitimi olmaz.', en: 'Original quality is preserved after processing, no pixel loss.', es: 'Calidad preservada tras proceso, sin pérdida de píxeles.', fr: 'Qualité originale préservée après traitement, aucune perte.', de: 'Ursprungsqualität bleibt erhalten, kein Pixelverlust.', it: 'Qualità mantenuta, nessuna perdita di pixel.', pt: 'Qualidade preservada, sem perda de pixels.', ja: '処理後も元の品質を維持、ピクセル劣化なし。', ru: 'Качество сохраняется после обработки, без потери пикселей.', ko: '처리 후 원본 품질이 유지되며 픽셀 손실이 없습니다.', zh: '处理后保持原始质量，无像素丢失。', zt: '處理後保持原始品質，無像素遺失。', ar: 'يتم حفظ الجودة الأصلية بعد المعالجة، لا يوجد فقدان للبيانات.', bg: 'Оригиналното качество се запазва, без загуба на пиксели.', ca: 'Es preserva la qualitat original, sense pèrdua de píxels.', nl: 'Originele kwaliteit blijft behouden, geen vermindering in pixels.', el: 'Η αρχική ποιότητα διατηρείται, χωρίς απώλεια pixel.', hi: 'संसाधन के बाद मूल गुणवत्ता बरकरार, पिक्सेल हानि नहीं।', id: 'Kualitas asal terjaga, tak ada piksel yang hilang.', ms: 'Kualiti asal dipelihara, tiada kehilangan piksel.', pl: 'Oryginalna jakość zostaje zachowana po przetwarzaniu.', sv: 'Originalkvalitet bevaras, ingen förlust av pixlar.', th: 'รักษาคุณภาพเดิม ไม่สูญเสียพิกเซล', uk: 'Оригінальна якість зберігається, без втрати пікселів.', vi: 'Giữ nguyên chất lượng như ban đầu, không bị mất nét.' },
    
    // faq
    'faq-badge': { tr: 'SSS', en: 'FAQ', es: 'Preguntas', fr: 'FAQ', de: 'FAQ', it: 'FAQ', pt: 'FAQ', ja: 'よくある質問', ru: 'ЧАВО', ko: '자주 묻는 질문', zh: '常见问题', zt: '常見問題', ar: 'الأسئلة الشائعة', bg: 'ЧЗВ', ca: 'Preguntes', nl: 'FAQ', el: 'Συχνές ερωτήσεις', hi: 'सामान्य प्रश्न', id: 'FAQ', ms: 'Soalan Lazim', pl: 'FAQ', sv: 'Vanliga frågor', th: 'คำถามที่พบบ่อย', uk: 'Питання', vi: 'Câu hỏi' },
    'faq-title': { tr: 'Sıkça Sorulan Sorular', en: 'Frequently Asked Questions', es: 'Preguntas Frecuentes', fr: 'Foire Aux Questions', de: 'Häufig gestellte Fragen', it: 'Domande Frequenti', pt: 'Perguntas Frequentes', ja: 'よくある質問', ru: 'Часто задаваемые вопросы', ko: '자주 묻는 질문', zh: '常见问题解答', zt: '常見問題解答', ar: 'الأسئلة الشائعة', bg: 'Често задавани въпроси', ca: 'Preguntes Freqüents', nl: 'Veelgestelde Vragen', el: 'Συχνές Ερωτήσεις', hi: 'अक्सर पूछे जाने वाले प्रश्न', id: 'Pertanyaan yang Sering Diajukan', ms: 'Sering Ditanya', pl: 'Często zadawane pytania', sv: 'Vanliga Frågor', th: 'คำถามที่พบบ่อย', uk: 'Часті питання', vi: 'Câu hỏi thường gặp' },
    'faq-q1': { tr: 'Dosyalarım güvende mi?', en: 'Are my files safe?', es: '¿Están seguros mis archivos?', fr: 'Mes fichiers sont-ils en sécurité ?', de: 'Sind meine Dateien sicher?', it: 'I miei file sono al sicuro?', pt: 'Meus arquivos estão seguros?', ja: 'ファイルは安全ですか？', ru: 'Мои файлы в безопасности?', ko: '내 파일은 안전한가요?', zh: '我的文件安全吗？', zt: '我的檔案安全嗎？', ar: 'هل ملفاتي آمنة؟', bg: 'В безопасност ли са файловете ми?', ca: 'Són segurs els meus fitxers?', nl: 'Zijn mijn bestanden veilig?', el: 'Είναι ασφαλή τα αρχεία μου;', hi: 'क्या मेरी फाइलें सुरक्षित हैं?', id: 'Apakah file saya aman?', ms: 'Adakah fail saya selamat?', pl: 'Czy moje pliki są bezpieczne?', sv: 'Är mina filer säkra?', th: 'ไฟล์ของฉันปลอดภัยไหม?', uk: 'Чи мої файли безпечні?', vi: 'Các tệp của tôi có an toàn không?' },
    'faq-a1': { tr: 'Evet. Tüm işlemler tarayıcınızda gerçekleşir. Dosyalarınız hiçbir zaman sunucularımıza yüklenmez, gizliliğiniz tamamen korunur.', en: 'Yes. All processing happens in your browser. Your files are never uploaded to our servers, keeping your privacy completely secure.', es: 'Sí. Todo se procesa en tu navegador. Tus archivos no se suben a nuestros servidores.', fr: 'Oui. Fichiers traités en local. Rien n\'est envoyé sur nos serveurs.', de: 'Ja. Alles wird lokal verarbeitet. Nichts wird hochgeladen.', it: 'Sì. Tutto elaborato localmente. Nessun file viene inviato.', pt: 'Sim. Tudo processado localmente. Nada é enviado para o servidor.', ja: 'はい。すべてローカルで処理され、サーバーにはアップロードされません。', ru: 'Да. Все локально, файлы никуда не загружаются.', ko: '예. 브라우저에서 실행되며 서버에 업로드되지 않습니다.', zh: '安全。所有处理都在浏览器本地完成，绝不上传服务器。', zt: '安全。所有處理都在瀏覽器本地完成，絕不上傳伺服器。', ar: 'نعم. كل شيء محلي ولا يرفع لأي خادم حفاظاً على الخصوصية.', bg: 'Да. Всичко е локално. Файловете ви не се качват в облака.', ca: 'Sí. Processament local, els fitxers mai es pugen a la xarxa.', nl: 'Ja, volledig lokaal. Je gegevens lekken nooit.', el: 'Ναι. Τοπική επεξεργασία χωρίς μεταφόρτωση δεδομένων.', hi: 'हाँ। सब कुछ केवल आपके ब्राउज़र में होता है।', id: 'Ya. Pengolahan lokal, tidak diunggah sama sekali.', ms: 'Ya. Semuanya selamat dalam peranti anda sendiri.', pl: 'Tak. Pliki są bezpieczne i nie są wysyłane w sieć.', sv: 'Ja, all hantering sker i webbläsaren. Data laddas inte upp.', th: 'ปลอดภัย 100% กระบวนการทั้งหมดเสร็จสิ้นบนเครื่องของคุณเอง', uk: 'Так. Абсолютна безпека завдяки обробці у веб-переглядачі.', vi: 'Có, các tệp luôn an toàn ngay trên trình duyệt mà không cần gửi đi.' },
    'faq-q2': { tr: 'Dosya boyutu sınırı var mı?', en: 'Is there a file size limit?', es: '¿Hay un límite de tamaño de archivo?', fr: 'Y a-t-il une limite de taille ?', de: 'Gibt es ein Dateigrößenlimit?', it: 'C\'è un limite alla dimensione?', pt: 'Existe limite de tamanho?', ja: 'ファイルサイズの制限は？', ru: 'Есть ограничение на размер?', ko: '파일 크기 제한이 있나요?', zh: '有大小限制吗？', zt: '有大小限制嗎？', ar: 'هل يوجد حدود للحجم؟', bg: 'Има ли лимит за размера?', ca: 'Límit de mida?', nl: 'Is er een groottelimiet?', el: 'Υπάρχει όριο μεγέθους;', hi: 'क्या कोई आकार सीमा है?', id: 'Ada batas ukuran file?', ms: 'Ada had saiz fail?', pl: 'Czy jest limit rozmiaru?', sv: 'Finns det en gräns för filstorlek?', th: 'มีข้อจำกัดขนาดมั้ย?', uk: 'Яке обмеження на розмір?', vi: 'Có giới hạn dung lượng?' },
    'faq-a2': { tr: 'Client-side işlem yaptığı için sınır tarayıcınızın RAM kapasitesiyle belirlenir. Genellikle 500MB\'a kadar sorunsuz çalışır.', en: 'It depends on your browser RAM. Usually works fine up to 500MB.', es: 'Depende de la RAM de tu navegador, manejando hasta 500 MB.', fr: 'Dépend de votre RAM, généralement jusqu\'à 500 Mo.', de: 'Hängt von Ihrem RAM ab (oft problemlos bis 500 MB).', it: 'Dipende dalla tua RAM (di solito fino a 500 MB).', pt: 'Depende da RAM, geralmente funciona até 500 MB.', ja: 'ブラウザのRAM依存です。通常500MBまでは問題ありません。', ru: 'Зависит от RAM, работает стабильно до 500 МБ.', ko: '브라우저 기기 성능에 따르며, 약 500MB까지 무난합니다.', zh: '取决于浏览器内存，通常500MB以内文件没问题。', zt: '取決於瀏覽器記憶體，通常500MB以內檔案沒問題。', ar: 'تعتمد على الرام الخاص بجهازك، يعمل حتى 500 ميغابايت بشكل عام.', bg: 'Зависи от RAM паметта ви. Файлове до 500MB работят гладко.', ca: 'Depèn de la teva RAM, fins a uns 500MB.', nl: 'Afhankelijk van RAM, zo rond de 500MB.', el: 'Εξαρτάται από το RAM σας, συνήθως έως 500MB.', hi: 'आपके RAM पर निर्भर है, अक्सर 500MB तक काम करता है।', id: 'Tergantung RAM perangkat. Mudah menyanggupi s.d 500 MB.', ms: 'Bergantung kpd RAM anda. Berfungsi dgn baik s.d 500MB.', pl: 'Wydajność zależy od RAMu, bezproblemowo obsługuje około 500MB.', sv: 'Beroende på minnet drar webbläsaren upp till 500MB.', th: 'ขึ้นกับความจุแรมเครื่องโดยรวม ใช้ได้สเถียรระดับไฟล์ 500MB.', uk: 'Прямопропорційно до RAM. Працює стабільно до 500МБ.', vi: 'Phụ thuộc vào dung lượng RAM tối đa, hoạt động ổn áp dưới 500MB.' },
    'faq-q3': { tr: 'Kayıt olmak gerekiyor mu?', en: 'Do I need to sign up?', es: '¿Necesito registrarme?', fr: 'Inscription requise ?', de: 'Registrierung nötig?', it: 'Devo registrarmi?', pt: 'Preciso me inscrever?', ja: '登録は必要ですか？', ru: 'Нужна регистрация?', ko: '회원가입이 필요한가요?', zh: '需要注册吗？', zt: '需要註冊嗎？', ar: 'هل أحتاج للتسجيل؟', bg: 'Трябва ли да се регистрирам?', ca: 'M\'he de registrar?', nl: 'Aanmelden?', el: 'Πρέπει να εγγραφώ;', hi: 'क्या पंजीकरण ज़रूरी है?', id: 'Perlu mendaftar?', ms: 'Kena daftar?', pl: 'Trzeba się rejestrować?', sv: 'Behövs inloggning?', th: 'ต้องสมัครสมาชิกไหม?', uk: 'Потрібна реєстрація?', vi: 'Cần tài khoản không?' },
    'faq-a3': { tr: 'Hayır. Tüm araçları kayıt olmadan ve ücretsiz kullanabilirsiniz. E-posta adresi bile gerekmez.', en: 'No. You can use all tools without registration. Not even an email is needed.', es: 'No. Puedes usar todo sin registro y de forma gratuita.', fr: 'Non. Outils gratuits et sans inscription.', de: 'Nein. Alles ohne Registrierung nutzbar frei.', it: 'No. Puoi usarlo senza alcuna registrazione.', pt: 'Não. Uso totalmente sem criar uma conta.', ja: 'いいえ。メールアドレスなども不要で無料利用可能です。', ru: 'Нет. Все бесплатно и без привязки вашей почты.', ko: '아니요. 계정 생성 없이 전면 무료입니다.', zh: '不需要，完全免费免洗。', zt: '無須，完全免費免洗。', ar: 'كلا، استخدمه مجانًا بلا حساب أو بريد.', bg: 'Не, достъпно е без никакви профили или имейли.', ca: 'No. Pots utilitzar el projecte sense donar dades.', nl: 'Nee. Vrij toegankelijk zonder formulier.', el: 'Όχι, χρησιμοποιήστε τα πάντα χωρίς κωδικούς.', hi: 'नहीं। आप मुफ्त में बिना लॉगिन उपयोग करें।', id: 'Tidak. Dapat digunakan tanpa mendaftar sepersen pun.', ms: 'Tiada pendaftaran diminta.', pl: 'Nie, wszystko działa z wejścia bez logina.', sv: 'Nej. Vi samlar inga mejlar. Gratis direkt.', th: 'ไม่จำเป็นใดๆ ใช้งานได้ฟรีทันที.', uk: 'Ні. Вільне користування без кабінетів.', vi: 'Tuyệt đối không. Không bắt đăng ký.' },
    'faq-q4': { tr: 'Hangi tarayıcılar destekleniyor?', en: 'Which browsers are supported?', es: 'Navegadores compatibles', fr: 'Navigateurs pris en charge', de: 'Unterstützte Browser', it: 'Browser supportati', pt: 'Navegadores suportados', ja: 'サポートブラウザは？', ru: 'Какие браузеры?', ko: '지원되는 브라우저는?', zh: '支持浏览器', zt: '支援瀏覽器', ar: 'المتصفحات المدعومة', bg: 'Поддържани браузъри', ca: 'Navegadors suportats', nl: 'Ondersteunde Browsers', el: 'Συμβατά Browser', hi: 'समर्थित ब्राउज़र्स', id: 'Browser yang Didukung', ms: 'Pelayar Pilihan', pl: 'Wspierane przeglądarki', sv: 'Stödda webbläsare', th: 'เบราว์เซอร์ที่รองรับ', uk: 'Браузери, що підтримуються', vi: 'Trình duyệt tương thích' },
    'faq-a4': { tr: 'Chrome, Firefox, Safari, Edge gibi modern tarayıcıların son sürümleri tam desteklenmektedir.', en: 'Modern browsers like Chrome, Firefox, Safari, and Edge are fully supported.', es: 'Chrome, Firefox, Safari y Edge recientes son totalmente compatibles.', fr: 'Chrome, Firefox, Safari et Edge récents sont compatibles.', de: 'Chrome, Firefox, Safari und Edge werden vollständig unterstützt.', it: 'Supporta in pieno Chrome, Firefox, Edge, e Safari.', pt: 'Funciona perfeitamente em Chrome, Firefox, Safari e Edge.', ja: 'Chrome, Firefox, Safari, Edgeなど各最新ブラウザをフルサポート。', ru: 'Полностью поддерживаются Chrome, Firefox, Safari и Edge.', ko: '크롬, 파이어폭스, 사파리, 엣지의 최신 버전을 전적 지원합니다.', zh: '全面支持Chrome、Firefox、Safari和Edge。', zt: '全面支援Chrome、Firefox、Safari和Edge。', ar: 'متوافق مع كروم وسفاري وفايرفوكس وإيدج الحديثة.', bg: 'Хром, Файърфокс, Сафари и Едж.', ca: 'Chrome, Firefox, Safari, Edge moderns.', nl: 'Laatste versies van Chrome, Firefox, Edge en Safari.', el: 'Τα σύγχρονα Chrome, Edge, Safari και Firefox.', hi: 'नए क्रोम, सफारी, मोज़िला, एज सपोर्टेड।', id: 'Sangat cocok untuk Chrome, Firefox, Edge, Safari versi kekinian.', ms: 'Terkini dari Chrome, Firefox, Edge dll.', pl: 'Oparte na nowym Chrome, Safari, FF i Edgu.', sv: 'Sömlös på senaste Chrome, Firefox, Safari och Edge.', th: 'รองรับบราวเซอร์ Chrome, Safari, Edge ตลอดจน Firefox.', uk: 'Останні версії Edge, Chrome, Firefox та Safari повністю підтримуються.', vi: 'Hoạt động mượt mà trên các bản mới của Firefox, Edge, Chrome.' },

    // tools section
    'sec-tools-badge': { tr: 'Araçlar', en: 'Tools', es: 'Herramientas', fr: 'Outils', de: 'Werkzeuge', it: 'Strumenti', pt: 'Ferramentas', ja: 'ツール', ru: 'Инструменты', ko: '도구', zh: '工具', zt: '工具', ar: 'الأدوات', bg: 'Инструменти', ca: 'Eines', nl: 'Hulpmiddelen', el: 'Εργαλεία', hi: 'उपकरण', id: 'Alat', ms: 'Alat', pl: 'Narzędzia', sv: 'Verktyg', th: 'เครื่องมือ', uk: 'Інструменти', vi: 'Công cụ' },
    'sec-tools-title': { tr: 'İhtiyacınız olan her şey', en: 'Everything you need', es: 'Todo lo que necesitas', fr: 'Tout ce dont vous avez besoin', de: 'Alles was Sie brauchen', it: 'Tutto ciò che serve', pt: 'Tudo que você precisa', ja: '必要なすべて', ru: 'Всё что нужно', ko: '필요한 모든 것', zh: '您需要的一切', zt: '您需要的一切', ar: 'كل ما تحتاجه', bg: 'Всичко необходимо', ca: 'Tot el que necessites', nl: 'Alles wat u nodig heeft', el: 'Όλα όσα χρειάζεστε', hi: 'जो चाहिए सब', id: 'Semua yang Anda butuhkan', ms: 'Semua yang anda perlukan', pl: 'Wszystko czego potrzebujesz', sv: 'Allt du behöver', th: 'ทุกอย่างที่คุณต้องการ', uk: 'Усе що потрібно', vi: 'Tất cả những gì bạn cần' },
    // category filter
    'cat-all': { tr: 'Tümü', en: 'All', es: 'Todos', fr: 'Tous', de: 'Alle', it: 'Tutti', pt: 'Todos', ja: 'すべて', ru: 'Все', ko: '전체', zh: '全部', zt: '全部', ar: 'الكل', bg: 'Всички', ca: 'Tots', nl: 'Alle', el: 'Όλα', hi: 'सभी', id: 'Semua', ms: 'Semua', pl: 'Wszystkie', sv: 'Alla', th: 'ทั้งหมด', uk: 'Усі', vi: 'Tất cả' },
    'cat-organize': { tr: 'Düzenle', en: 'Organize', es: 'Organizar', fr: 'Organiser', de: 'Organisieren', it: 'Organizza', pt: 'Organizar', ja: '整理', ru: 'Организовать', ko: '정리', zh: '整理', zt: '整理', ar: 'تنظيم', bg: 'Организирайте', ca: 'Organitza', nl: 'Organiseren', el: 'Οργάνωση', hi: 'व्यवस्थित', id: 'Atur', ms: 'Susun', pl: 'Organizuj', sv: 'Organisera', th: 'จัดระเบียบ', uk: 'Впорядкувати', vi: 'Sắp xếp' },
    'cat-convert': { tr: 'Dönüştür', en: 'Convert', es: 'Convertir', fr: 'Convertir', de: 'Konvertieren', it: 'Converti', pt: 'Converter', ja: '変換', ru: 'Конвертировать', ko: '변환', zh: '转换', zt: '轉換', ar: 'تحويل', bg: 'Конвертирайте', ca: 'Converteix', nl: 'Converteren', el: 'Μετατροπή', hi: 'रूपांतरित', id: 'Konversi', ms: 'Tukar', pl: 'Konwertuj', sv: 'Konvertera', th: 'แปลง', uk: 'Конвертувати', vi: 'Chuyển đổi' },
    'cat-security': { tr: 'Güvenlik', en: 'Security', es: 'Seguridad', fr: 'Sécurité', de: 'Sicherheit', it: 'Sicurezza', pt: 'Segurança', ja: 'セキュリティ', ru: 'Безопасность', ko: '보안', zh: '安全', zt: '安全', ar: 'الأمان', bg: 'Сигурност', ca: 'Seguretat', nl: 'Beveiliging', el: 'Ασφάλεια', hi: 'सुरक्षा', id: 'Keamanan', ms: 'Keselamatan', pl: 'Bezpieczeństwo', sv: 'Säkerhet', th: 'ความปลอดภัย', uk: 'Безпека', vi: 'Bảo mật' },
    'cat-optimize': { tr: 'Optimize', en: 'Optimize', es: 'Optimizar', fr: 'Optimiser', de: 'Optimieren', it: 'Ottimizza', pt: 'Otimizar', ja: '最適化', ru: 'Оптимизировать', ko: '최적화', zh: '优化', zt: '優化', ar: 'تحسين', bg: 'Оптимизирайте', ca: 'Optimitza', nl: 'Optimaliseren', el: 'Βελτιστοποίηση', hi: 'अनुकूलित', id: 'Optimalkan', ms: 'Optimumkan', pl: 'Optymalizuj', sv: 'Optimera', th: 'ปรับปรุง', uk: 'Оптимізувати', vi: 'Tối ưu hóa' },
    // tool names
    'tool-merge': { tr: 'PDF Birleştir', en: 'Merge PDF', es: 'Combinar PDF', fr: 'Fusionner PDF', de: 'PDF Zusammenführen', it: 'Unisci PDF', pt: 'Mesclar PDF', ja: 'PDF結合', ru: 'Объединить PDF', ko: 'PDF 합치기', zh: '合并PDF', zt: '合併PDF', ar: 'دمج PDF', bg: 'Обедини PDF', ca: 'Unir PDF', nl: 'PDF Samenvoegen', el: 'Ένωση PDF', hi: 'PDF मर्ज करें', id: 'Gabung PDF', ms: 'Gabung PDF', pl: 'Połącz PDF', sv: 'Slå Ihop PDF', th: 'รวม PDF', uk: 'Об\'єднати PDF', vi: 'Gộp PDF' },
    'tool-split': { tr: 'PDF Böl', en: 'Split PDF', es: 'Dividir PDF', fr: 'Diviser PDF', de: 'PDF Teilen', it: 'Dividi PDF', pt: 'Dividir PDF', ja: 'PDF分割', ru: 'Разделить PDF', ko: 'PDF 분할', zh: '拆分PDF', zt: '拆分PDF', ar: 'تقسيم PDF', bg: 'Раздели PDF', ca: 'Divideix PDF', nl: 'PDF Splitsen', el: 'Διαχωρισμός PDF', hi: 'PDF विभाजित', id: 'Pisah PDF', ms: 'Pisah PDF', pl: 'Podziel PDF', sv: 'Dela PDF', th: 'แบ่ง PDF', uk: 'Розділити PDF', vi: 'Tách PDF' },
    'tool-compress': { tr: 'PDF Sıkıştır', en: 'Compress PDF', es: 'Comprimir PDF', fr: 'Compresser PDF', de: 'PDF Komprimieren', it: 'Comprimi PDF', pt: 'Comprimir PDF', ja: 'PDF圧縮', ru: 'Сжать PDF', ko: 'PDF 압축', zh: '压缩PDF', zt: '壓縮PDF', ar: 'ضغط PDF', bg: 'Компресирай PDF', ca: 'Comprimeix PDF', nl: 'PDF Comprimeren', el: 'Συμπίεση PDF', hi: 'PDF को संपीड़ित', id: 'Kompres PDF', ms: 'Mampat PDF', pl: 'Kompresuj PDF', sv: 'Komprimera PDF', th: 'บีบอัด PDF', uk: 'Стиснути PDF', vi: 'Nén PDF' },
    'tool-rotate': { tr: 'PDF Döndür', en: 'Rotate PDF', es: 'Rotar PDF', fr: 'Pivoter PDF', de: 'PDF Drehen', it: 'Ruota PDF', pt: 'Girar PDF', ja: 'PDF回転', ru: 'Повернуть PDF', ko: 'PDF 회전', zh: '旋转PDF', zt: '旋轉PDF', ar: 'تدوير PDF', bg: 'Завърти PDF', ca: 'Gira PDF', nl: 'PDF Roteren', el: 'Περιστροφή PDF', hi: 'PDF घुमाएं', id: 'Putar PDF', ms: 'Putar PDF', pl: 'Obróć PDF', sv: 'Rotera PDF', th: 'หมุน PDF', uk: 'Повернути PDF', vi: 'Xoay PDF' },
    'tool-pdf-to-word': { tr: 'PDF → Word', en: 'PDF to Word', es: 'PDF a Word', fr: 'PDF en Word', de: 'PDF zu Word', it: 'PDF in Word', pt: 'PDF para Word', ja: 'PDFからWord', ru: 'PDF в Word', ko: 'PDF를 Word로', zh: 'PDF转Word', zt: 'PDF轉Word', ar: 'PDF إلى Word', bg: 'PDF към Word', ca: 'PDF a Word', nl: 'PDF naar Word', el: 'PDF σε Word', hi: 'PDF से Word', id: 'PDF ke Word', ms: 'PDF ke Word', pl: 'PDF do Word', sv: 'PDF till Word', th: 'PDF เป็น Word', uk: 'PDF у Word', vi: 'PDF sang Word' },
    'tool-pdf-to-jpg': { tr: 'PDF → JPG', en: 'PDF to JPG', es: 'PDF a JPG', fr: 'PDF en JPG', de: 'PDF zu JPG', it: 'PDF in JPG', pt: 'PDF para JPG', ja: 'PDFからJPG', ru: 'PDF в JPG', ko: 'PDF를 JPG로', zh: 'PDF转JPG', zt: 'PDF轉JPG', ar: 'PDF إلى JPG', bg: 'PDF към JPG', ca: 'PDF a JPG', nl: 'PDF naar JPG', el: 'PDF σε JPG', hi: 'PDF से JPG', id: 'PDF ke JPG', ms: 'PDF ke JPG', pl: 'PDF do JPG', sv: 'PDF till JPG', th: 'PDF เป็น JPG', uk: 'PDF у JPG', vi: 'PDF sang JPG' },
    'tool-jpg-to-pdf': { tr: 'JPG → PDF', en: 'JPG to PDF', es: 'JPG a PDF', fr: 'JPG en PDF', de: 'JPG zu PDF', it: 'JPG in PDF', pt: 'JPG para PDF', ja: 'JPGからPDF', ru: 'JPG в PDF', ko: 'JPG를 PDF로', zh: 'JPG转PDF', zt: 'JPG轉PDF', ar: 'JPG إلى PDF', bg: 'JPG към PDF', ca: 'JPG a PDF', nl: 'JPG naar PDF', el: 'JPG σε PDF', hi: 'JPG से PDF', id: 'JPG ke PDF', ms: 'JPG ke PDF', pl: 'JPG do PDF', sv: 'JPG till PDF', th: 'JPG เป็น PDF', uk: 'JPG у PDF', vi: 'JPG sang PDF' },
    'tool-word-to-pdf': { tr: 'Word → PDF', en: 'Word to PDF', es: 'Word a PDF', fr: 'Word en PDF', de: 'Word zu PDF', it: 'Word in PDF', pt: 'Word para PDF', ja: 'WordからPDF', ru: 'Word в PDF', ko: 'Word를 PDF로', zh: 'Word转PDF', zt: 'Word轉PDF', ar: 'Word إلى PDF', bg: 'Word към PDF', ca: 'Word a PDF', nl: 'Word naar PDF', el: 'Word σε PDF', hi: 'Word से PDF', id: 'Word ke PDF', ms: 'Word ke PDF', pl: 'Word do PDF', sv: 'Word till PDF', th: 'Word เป็น PDF', uk: 'Word у PDF', vi: 'Word sang PDF' },
    'tool-excel-to-pdf': { tr: 'Excel → PDF', en: 'Excel to PDF', es: 'Excel a PDF', fr: 'Excel en PDF', de: 'Excel zu PDF', it: 'Excel in PDF', pt: 'Excel para PDF', ja: 'ExcelからPDF', ru: 'Excel в PDF', ko: 'Excel을 PDF로', zh: 'Excel转PDF', zt: 'Excel轉PDF', ar: 'Excel إلى PDF', bg: 'Excel към PDF', ca: 'Excel a PDF', nl: 'Excel naar PDF', el: 'Excel σε PDF', hi: 'Excel से PDF', id: 'Excel ke PDF', ms: 'Excel ke PDF', pl: 'Excel do PDF', sv: 'Excel till PDF', th: 'Excel เป็น PDF', uk: 'Excel у PDF', vi: 'Excel sang PDF' },
    'tool-watermark': { tr: 'Filigran Ekle', en: 'Add Watermark', es: 'Agregar marca de agua', fr: 'Ajouter un filigrane', de: 'Wasserzeichen einfügen', it: 'Aggiungi filigrana', pt: 'Adicionar marca d\'água', ja: '透かしを追加', ru: 'Добавить водяной знак', ko: '워터마크 추가', zh: '添加水印', zt: '添加浮水印', ar: 'إضافة علامة مائية', bg: 'Добави воден знак', ca: 'Afegir filigrana', nl: 'Watermerk Toevoegen', el: 'Προσθήκη υδατογραφήματος', hi: 'वॉटरमार्क जोड़ें', id: 'Tambah Watermark', ms: 'Tambah Tera Air', pl: 'Dodaj Znak Wodny', sv: 'Lägg till vattenstämpel', th: 'เพิ่มลายน้ำ', uk: 'Додати водяний знак', vi: 'Thêm Hình mờ' },
    'tool-protect': { tr: 'PDF Şifrele', en: 'Protect PDF', es: 'Proteger PDF', fr: 'Protéger PDF', de: 'PDF Schützen', it: 'Proteggi PDF', pt: 'Proteger PDF', ja: 'PDFを保護', ru: 'Защитить PDF', ko: 'PDF 보호', zh: '加密PDF', zt: '加密PDF', ar: 'حماية PDF', bg: 'Защити PDF', ca: 'Protegeix PDF', nl: 'PDF Beveiligen', el: 'Προστασία PDF', hi: 'PDF की सुरक्षा', id: 'Lindungi PDF', ms: 'Lindungi PDF', pl: 'Chroń PDF', sv: 'Skydda PDF', th: 'ป้องกัน PDF', uk: 'Захистити PDF', vi: 'Bảo vệ PDF' },
    'tool-unlock': { tr: 'PDF Kilidi Aç', en: 'Unlock PDF', es: 'Desbloquear PDF', fr: 'Déverrouiller PDF', de: 'PDF Entsperren', it: 'Sblocca PDF', pt: 'Desbloquear PDF', ja: 'PDFのロック解除', ru: 'Разблокировать PDF', ko: 'PDF 잠금 해제', zh: '解锁PDF', zt: '解鎖PDF', ar: 'إلغاء قفل PDF', bg: 'Отключи PDF', ca: 'Desbloqueja PDF', nl: 'PDF Ontgrendelen', el: 'Ξεκλείδωμα PDF', hi: 'PDF अनलॉक करें', id: 'Buka Kunci PDF', ms: 'Buka Kunci PDF', pl: 'Odblokuj PDF', sv: 'Lås upp PDF', th: 'ปลดล็อก PDF', uk: 'Розблокувати PDF', vi: 'Mở khóa PDF' },
    'tool-sign': { tr: 'PDF İmzala', en: 'Sign PDF', es: 'Firmar PDF', fr: 'Signer PDF', de: 'PDF Signieren', it: 'Firma PDF', pt: 'Assinar PDF', ja: 'PDF署名', ru: 'Подписать PDF', ko: 'PDF 서명', zh: '签署PDF', zt: '簽署PDF', ar: 'توقيع PDF', bg: 'Подпиши PDF', ca: 'Signa PDF', nl: 'PDF Ondertekenen', el: 'Υπογραφή PDF', hi: 'PDF हस्ताक्षर', id: 'Tandatangani PDF', ms: 'Tandatangan PDF', pl: 'Podpisz PDF', sv: 'Signera PDF', th: 'เซ็น PDF', uk: 'Підписати PDF', vi: 'Ký PDF' },
    'tool-pagenumbers': { tr: 'Sayfa Numarası Ekle', en: 'Add Page Numbers', es: 'Agregar números de página', fr: 'Ajouter numéros de page', de: 'Seitenzahlen einfügen', it: 'Aggiungi numeri pagina', pt: 'Adicionar números de página', ja: 'ページ番号を追加', ru: 'Добавить нумерацию страниц', ko: '페이지 번호 추가', zh: '添加页码', zt: '添加頁碼', ar: 'إضافة أرقام الصفحات', bg: 'Добави номера на страници', ca: 'Afegir numeració de pàgines', nl: 'Paginanummers Toevoegen', el: 'Προσθήκη αριθμών σελίδας', hi: 'पृष्ठ संख्या जोड़ें', id: 'Tambah Nomor Halaman', ms: 'Tambah Nombor Halaman', pl: 'Dodaj Numery Stron', sv: 'Lägg till sidnummer', th: 'เพิ่มเลขหน้า', uk: 'Додати номери сторінок', vi: 'Thêm số trang' },
    'tool-meta': { tr: 'Meta Düzenle', en: 'Edit Metadata', es: 'Editar metadatos', fr: 'Modifier les métadonnées', de: 'Metadaten bearbeiten', it: 'Modifica metadati', pt: 'Editar metadados', ja: 'メタデータ編集', ru: 'Редактировать метаданные', ko: '메타데이터 편집', zh: '编辑元数据', zt: '編輯元數據', ar: 'تعديل البيانات التعريفية', bg: 'Редактирай метаданни', ca: 'Edita metadades', nl: 'Metadata Bewerken', el: 'Επεξεργασία μεταδεδομένων', hi: 'मेटाडेटा संपादित करें', id: 'Edit Metadata', ms: 'Edit Metadata', pl: 'Edytuj metadane', sv: 'Redigera Metadata', th: 'แก้ไข Metadata', uk: 'Редагувати метадані', vi: 'Chỉnh sửa Metadata' },
    'tool-grayscale': { tr: 'Gri Tona Çevir', en: 'Convert to Grayscale', es: 'Convertir a escala de grises', fr: 'Convertir en niveaux de gris', de: 'In Graustufen konvertieren', it: 'Converti in scala di grigi', pt: 'Converter para escala de cinza', ja: 'グレースケールに変換', ru: 'Преобразовать в оттенки серого', ko: '흑백으로 변환', zh: '转换为灰度', zt: '轉換為灰度', ar: 'التحويل إلى الرمادي', bg: 'Преобрази в сиво', ca: 'Converteix a escala de grisos', nl: 'Omzetten naar grijstinten', el: 'Μετατροπή σε Γκρι', hi: 'ग्रेस्केल में बदलें', id: 'Konversi ke Skala Abu-abu', ms: 'Tukar ke Skala Kelabu', pl: 'Konwertuj do skali szarości', sv: 'Konvertera till gråskala', th: 'แปลงเป็นขาวดำ', uk: 'Перетворити на відтінки сірого', vi: 'Chuyển sang thang xám' },
    'tool-organize': { tr: 'Sayfaları Düzenle', en: 'Organize Pages', es: 'Organizar páginas', fr: 'Organiser les pages', de: 'Seiten organisieren', it: 'Organizza pagine', pt: 'Organizar páginas', ja: 'ページを整理', ru: 'Организовать страницы', ko: '페이지 정리', zh: '整理页面', zt: '整理頁面', ar: 'تنظيم الصفحات', bg: 'Организирай страниците', ca: 'Organitza pàgines', nl: 'Pagina\'s organiseren', el: 'Οργάνωση σελίδων', hi: 'पृष्ठ व्यवस्थित करें', id: 'Atur Halaman', ms: 'Susun Halaman', pl: 'Organizuj strony', sv: 'Organisera sidor', th: 'จัดระเบียบหน้า', uk: 'Впорядкувати сторінки', vi: 'Sắp xếp trang' },
    'tool-ocr': { tr: 'OCR PDF', en: 'OCR PDF', es: 'OCR PDF', fr: 'OCR PDF', de: 'OCR PDF', it: 'OCR PDF', pt: 'OCR PDF', ja: 'OCR PDF', ru: 'OCR PDF', ko: 'OCR PDF', zh: 'OCR PDF', zt: 'OCR PDF', ar: 'OCR PDF', bg: 'OCR PDF', ca: 'OCR PDF', nl: 'OCR PDF', el: 'OCR PDF', hi: 'OCR PDF', id: 'OCR PDF', ms: 'OCR PDF', pl: 'OCR PDF', sv: 'OCR PDF', th: 'OCR PDF', uk: 'OCR PDF', vi: 'OCR PDF' },
    'tool-merge-desc': { tr: 'Birden fazla PDF\'i tek bir belgede birleştirin', en: 'Merge multiple PDFs into one document', es: 'Combina múltiples PDFs en un solo documento', fr: 'Fusionnez plusieurs PDF en un seul document', de: 'Führen Sie mehrere PDFs in einem Dokument zusammen' },
    'tool-split-desc': { tr: 'PDF\'i sayfa aralıklarına göre parçalara ayırın', en: 'Split PDF by page ranges', es: 'Dividir PDF por rangos de páginas', fr: 'Diviser un PDF par plages de pages', de: 'PDF nach Seitenbereichen aufteilen' },
    'tool-compress-desc': { tr: 'Kaliteyi koruyarak dosya boyutunu küçültün', en: 'Reduce file size while preserving quality', es: 'Reduce el tamaño del archivo conservando la calidad', fr: 'Réduire la taille du fichier tout en conservant la qualité', de: 'Dateigröße bei gleichbleibender Qualität reduzieren' },
    'tool-rotate-desc': { tr: 'Sayfaları 90°, 180° veya 270° döndürün', en: 'Rotate pages by 90°, 180°, or 270°', es: 'Rotar páginas en 90°, 180° o 270°', fr: 'Faire pivoter les pages de 90°, 180° ou 270°', de: 'Seiten um 90°, 180° oder 270° drehen' },
    'tool-pdf-to-word-desc': { tr: 'PDF belgelerini düzenlenebilir Word formatına çevirin', en: 'Convert PDF documents to editable Word format', es: 'Convierta documentos PDF a formato Word editable', fr: 'Convertir des documents PDF au format Word modifiable', de: 'Konvertieren Sie PDF-Dokumente in ein bearbeitbares Word-Format' },
    'tool-pdf-to-jpg-desc': { tr: 'Her sayfayı yüksek kaliteli görüntüye dönüştürün', en: 'Convert each page to a high-quality image', es: 'Convierta cada página en una imagen de alta calidad', fr: 'Convertissez chaque page en une image de haute qualité', de: 'Konvertieren Sie jede Seite in ein hochwertiges Bild' },
    'tool-jpg-to-pdf-desc': { tr: 'Görüntülerinizi PDF belgelerine dönüştürün', en: 'Convert your images to PDF documents', es: 'Convierte tus imágenes a documentos PDF', fr: 'Convertissez vos images en documents PDF', de: 'Konvertieren Sie Ihre Bilder in PDF-Dokumente' },
    'tool-word-to-pdf-desc': { tr: 'Word belgelerini PDF formatına dönüştürün', en: 'Convert Word documents to PDF format', es: 'Convertir documentos de Word a formato PDF', fr: 'Convertir des documents Word au format PDF', de: 'Konvertieren Sie Word-Dokumente in das PDF-Format' },
    'tool-excel-to-pdf-desc': { tr: 'Excel tablolarını PDF olarak kaydedin', en: 'Save Excel spreadsheets as PDF', es: 'Guardar hojas de cálculo de Excel como PDF', fr: 'Enregistrer les feuilles de calcul Excel au format PDF', de: 'Excel-Tabellen als PDF speichern' },
    'tool-protect-desc': { tr: 'PDF\'inizi parola ile koruyun', en: 'Protect your PDF with a password', es: 'Protege tu PDF con una contraseña', fr: 'Protégez votre PDF avec un mot de passe', de: 'Schützen Sie Ihr PDF mit einem Passwort' },
    'tool-unlock-desc': { tr: 'Şifreli PDF\'den korumayı kaldırın', en: 'Remove protection from encrypted PDF', es: 'Eliminar protección de PDF encriptado', fr: 'Supprimer la protection d\'un PDF crypté', de: 'Schutz aus verschlüsseltem PDF entfernen' },
    'tool-watermark-desc': { tr: 'PDF sayfalarına metin veya logo filigranı ekleyin', en: 'Add text or logo watermark to PDF pages', es: 'Agregue marca de agua de texto o logotipo a páginas PDF', fr: 'Ajouter un filigrane de texte ou de logo aux pages PDF', de: 'Fügen Sie Text- oder Logo-Wasserzeichen zu PDF-Seiten hinzu' },
    'tool-sign-desc': { tr: 'El yazısı imzanızı PDF\'e ekleyin', en: 'Add your handwritten signature to the PDF', es: 'Agrega tu firma manuscrita al PDF', fr: 'Ajoutez votre signature manuscrite au PDF', de: 'Fügen Sie dem PDF Ihre handschriftliche Unterschrift hinzu' },
    'tool-pagenumbers-desc': { tr: 'Her sayfaya otomatik numara ekleyin', en: 'Add automatic page numbers to each page', es: 'Agregar números de página automáticos a cada página', fr: 'Ajouter des numéros de page automatiques à chaque page', de: 'Fügen Sie jeder Seite automatische Seitenzahlen hinzu' },
    'tool-meta-desc': { tr: 'PDF başlık, yazar ve konu bilgilerini düzenleyin', en: 'Edit PDF title, author, and subject information', es: 'Editar título de PDF, autor e información del asunto', fr: 'Modifier le titre, l\'auteur et le sujet du PDF', de: 'Bearbeiten Sie Titel, Autor und Betreff-Informationen im PDF' },
    'tool-grayscale-desc': { tr: 'Renkli PDF\'i siyah-beyaz yapın, boyutu küçültün', en: 'Make color PDF black-and-white, reduce size', es: 'Haga el PDF en color en blanco y negro, reduzca el tamaño', fr: 'Mettre le PDF couleur en noir et blanc, réduire la taille', de: 'Farbiges PDF auf Schwarzweiß umstellen, Größe reduzieren' },
    // modal / processing UI
    'drop-hint': { tr: 'Dosyayı buraya sürükleyin veya seçin', en: 'Drop file here or click to select', es: 'Arrastre el archivo aquí o haga clic', fr: 'Déposez le fichier ici ou cliquez', de: 'Datei hier ablegen oder klicken', it: 'Trascina il file qui o clicca', pt: 'Solte o arquivo aqui ou clique', ja: 'ファイルをドロップまたはクリック', ru: 'Перетащите файл или нажмите', ko: '파일을 여기에 놓거나 클릭', zh: '拖放文件到此处或点击', zt: '拖放文件到此處或點擊', ar: 'اسحب الملف هنا أو انقر', bg: 'Пуснете файла тук или кликнете', ca: 'Arrossega el fitxer aquí o fes clic', nl: 'Sleep bestand hier of klik', el: 'Σύρετε το αρχείο εδώ ή κάντε κλικ', hi: 'फ़ाइल यहाँ छोड़ें या क्लिक करें', id: 'Seret file ke sini atau klik', ms: 'Seret fail di sini atau klik', pl: 'Upuść plik tutaj lub kliknij', sv: 'Släpp filen här eller klicka', th: 'ลากไฟล์มาที่นี่หรือคลิก', uk: 'Перетягніть файл або клацніть', vi: 'Kéo tệp vào đây hoặc nhấp' },
    'select-file': { tr: 'Dosya Seç', en: 'Select File', es: 'Seleccionar archivo', fr: 'Sélectionner le fichier', de: 'Datei auswählen', it: 'Seleziona file', pt: 'Selecionar arquivo', ja: 'ファイルを選択', ru: 'Выбрать файл', ko: '파일 선택', zh: '选择文件', zt: '選擇文件', ar: 'اختر ملفاً', bg: 'Изберете файл', ca: 'Selecciona fitxer', nl: 'Bestand selecteren', el: 'Επιλογή αρχείου', hi: 'फ़ाइल चुनें', id: 'Pilih File', ms: 'Pilih Fail', pl: 'Wybierz plik', sv: 'Välj fil', th: 'เลือกไฟล์', uk: 'Вибрати файл', vi: 'Chọn tệp' },
    'processing': { tr: 'İşleniyor…', en: 'Processing…', es: 'Procesando…', fr: 'Traitement…', de: 'Verarbeitung…', it: 'Elaborazione…', pt: 'Processando…', ja: '処理中…', ru: 'Обработка…', ko: '처리 중…', zh: '处理中…', zt: '處理中…', ar: 'جارٍ المعالجة…', bg: 'Обработва се…', ca: 'Processant…', nl: 'Verwerken…', el: 'Επεξεργασία…', hi: 'प्रसंस्करण…', id: 'Memproses…', ms: 'Memproses…', pl: 'Przetwarzanie…', sv: 'Bearbetar…', th: 'กำลังประมวลผล…', uk: 'Обробка…', vi: 'Đang xử lý…' },
    'done': { tr: 'Tamamlandı!', en: 'Done!', es: '¡Listo!', fr: 'Terminé !', de: 'Fertig!', it: 'Fatto!', pt: 'Concluído!', ja: '完了！', ru: 'Готово!', ko: '완료!', zh: '完成！', zt: '完成！', ar: 'تم!', bg: 'Готово!', ca: 'Fet!', nl: 'Klaar!', el: 'Ολοκληρώθηκε!', hi: 'पूरा हुआ!', id: 'Selesai!', ms: 'Siap!', pl: 'Gotowe!', sv: 'Klart!', th: 'เสร็จสิ้น!', uk: 'Готово!', vi: 'Hoàn thành!' },
    'download': { tr: 'İndir', en: 'Download', es: 'Descargar', fr: 'Télécharger', de: 'Herunterladen', it: 'Scarica', pt: 'Baixar', ja: 'ダウンロード', ru: 'Скачать', ko: '다운로드', zh: '下载', zt: '下載', ar: 'تحميل', bg: 'Изтегли', ca: 'Descarrega', nl: 'Downloaden', el: 'Λήψη', hi: 'डाउनलोड', id: 'Unduh', ms: 'Muat turun', pl: 'Pobierz', sv: 'Ladda ner', th: 'ดาวน์โหลด', uk: 'Завантажити', vi: 'Tải xuống' },
    'result-ready': { tr: 'Dosyanız hazır', en: 'Your file is ready', es: 'Su archivo está listo', fr: 'Votre fichier est prêt', de: 'Ihre Datei ist fertig', it: 'Il tuo file è pronto', pt: 'Seu arquivo está pronto', ja: 'ファイルが準備できました', ru: 'Ваш файл готов', ko: '파일이 준비되었습니다', zh: '您的文件已准备好', zt: '您的文件已準備好', ar: 'ملفك جاهز', bg: 'Файлът е готов', ca: 'El fitxer és a punt', nl: 'Uw bestand is klaar', el: 'Το αρχείο σας είναι έτοιμο', hi: 'आपकी फ़ाइल तैयार है', id: 'File Anda siap', ms: 'Fail anda sedia', pl: 'Plik jest gotowy', sv: 'Din fil är klar', th: 'ไฟล์ของคุณพร้อมแล้ว', uk: 'Ваш файл готовий', vi: 'Tệp của bạn đã sẵn sàng' },
    'no-file': { tr: 'Lütfen önce bir dosya seçin.', en: 'Please select a file first.', es: 'Por favor seleccione un archivo.', fr: 'Veuillez sélectionner un fichier.', de: 'Bitte wählen Sie zuerst eine Datei.', it: 'Seleziona prima un file.', pt: 'Selecione primeiro um arquivo.', ja: 'まずファイルを選択してください。', ru: 'Пожалуйста, выберите файл.', ko: '먼저 파일을 선택하세요.', zh: '请先选择一个文件。', zt: '請先選擇一個文件。', ar: 'يرجى تحديد ملف أولاً.', bg: 'Моля изберете файл.', ca: 'Seleccioneu primer un fitxer.', nl: 'Selecteer eerst een bestand.', el: 'Επιλέξτε πρώτα ένα αρχείο.', hi: 'पहले एक फ़ाइल चुनें।', id: 'Silakan pilih file terlebih dahulu.', ms: 'Sila pilih fail dahulu.', pl: 'Najpierw wybierz plik.', sv: 'Välj en fil först.', th: 'กรุณาเลือกไฟล์ก่อน', uk: 'Будь ласка, виберіть файл.', vi: 'Vui lòng chọn một tệp trước.' },
    'tool-organize-desc': { tr: 'Sürükle-bırak ile sayfa sırasını değiştirin', en: 'Reorder pages with drag & drop', es: 'Reordenar páginas arrastrando', fr: 'Réorganiser les pages par glisser-déposer', de: 'Seiten per Drag & Drop neu anordnen', it: 'Riorganizza le pagine trascinando', pt: 'Reordenar páginas arrastando', ja: 'ドラッグで並べ替え', ru: 'Перенести страницы перетаскиванием', ko: '드래그로 페이지 재정렬', zh: '拖拽重新排列页面', zt: '拖放重新排列頁面', ar: 'إعادة ترتيب الصفحات بالسحب', bg: 'Пренаредете страниците с плъзгане', ca: 'Reordena pàgines arrossegant', nl: 'Paginasvolgorde wijzigen', el: 'Αναδιάταξη σελίδων με σύρσιμο', hi: 'खींचकर पृष्ठ क्रम बदलें', id: 'Susun ulang halaman dengan drag', ms: 'Susun semula halaman dengan seret', pl: 'Zmień kolejność stron przeciągając', sv: 'Ordna om sidor med drag', th: 'จัดเรียงหน้าด้วยการลาก', uk: 'Перетягніть для зміни порядку', vi: 'Sắp xếp lại trang bằng kéo thả' },
    'tool-ocr-desc': { tr: 'Taranmış PDF veya görüntüdeki metni tanıyın', en: 'Extract text from scanned PDF or image', es: 'Extraer texto de PDF escaneado', fr: 'Extraire le texte d\'un PDF scanné', de: 'Text aus gescanntem PDF extrahieren', it: 'Estrai testo da PDF scansionato', pt: 'Extraia texto de PDF digitalizado', ja: 'スキャンPDFからテキスト抽出', ru: 'Извлечь текст из сканированного PDF', ko: '스캔 PDF에서 텍스트 추출', zh: '从扫描PDF提取文字', zt: '從掃描PDF提取文字', ar: 'استخراج النص من PDF مسح ضوئي', bg: 'Извличане на текст от сканиран PDF', ca: 'Extreu text d\'un PDF escanejat', nl: 'Tekst uit gescand PDF halen', el: 'Εξαγωγή κειμένου από σαρωμένο PDF', hi: 'स्कैन PDF से टेक्स्ट निकालें', id: 'Ekstrak teks dari PDF pindaian', ms: 'Ekstrak teks dari PDF yang diimbas', pl: 'Wyodrębnij tekst ze zeskanowanego PDF', sv: 'Extrahera text från skannad PDF', th: 'แยกข้อความจาก PDF สแกน', uk: 'Витягти текст зі сканованого PDF', vi: 'Trích xuất văn bản từ PDF được quét' },
    // search
    'search-placeholder': { tr: 'Araç ara… (örn. birleştir, sıkıştır)', en: 'Search tools…', es: 'Buscar herramientas…', fr: 'Rechercher des outils…', de: 'Werkzeuge suchen…', it: 'Cerca strumenti…', pt: 'Buscar ferramentas…', ja: 'ツールを検索…', ru: 'Поиск инструментов…', ko: '도구 검색…', zh: '搜索工具…', zt: '搜尋工具…', ar: 'ابحث عن أدوات…', bg: 'Търсене на инструменти…', ca: 'Cerca eines…', nl: 'Zoek hulpmiddelen…', el: 'Αναζήτηση εργαλείων…', hi: 'टूल खोजें…', id: 'Cari alat…', ms: 'Cari alat…', pl: 'Szukaj narzędzi…', sv: 'Sök verktyg…', th: 'ค้นหาเครื่องมือ…', uk: 'Пошук інструментів…', vi: 'Tìm kiếm công cụ…' },
};

/* ── Core i18n engine ── */
function detectBrowserLang() {
    const nav = navigator.language || navigator.userLanguage || 'en';
    const langCode = nav.toLowerCase().split('-')[0];
    
    // Check for traditional chinese
    if (langCode === 'zh') {
        const full = nav.toLowerCase();
        if (full.includes('tw') || full.includes('hk') || full.includes('hant')) return 'zt';
        return 'zh';
    }
    
    // Check if we support this exact lang code
    if (window.PDFStar_LANGS[langCode]) {
        return langCode;
    }
    
    // Fallback to English
    return 'en';
}

// User preference or auto-detect browser language
let _currentLang = localStorage.getItem('PDFStar-lang') || detectBrowserLang();

function t(key) {
    const entry = window.T[key];
    if (!entry) return key;
    return entry[_currentLang] || entry['en'] || key;
}

function applyLang(lang) {
    _currentLang = lang;
    localStorage.setItem('PDFStar-lang', lang);
    const cfg = window.PDFStar_LANGS[lang];
    document.documentElement.lang = lang;
    document.documentElement.dir = cfg?.dir || 'ltr';

    // Update all data-i18n elements
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.dataset.i18n;
        const text = t(key);
        if (el.tagName === 'INPUT') el.placeholder = text;
        else el.innerHTML = text; // allow <br> to render in text
    });

    // Update lang dropdown label
    const btn = document.getElementById('langToggle');
    if (btn) btn.innerHTML = `${cfg?.flag || ''} ${cfg?.name || lang}`;

    // Update search placeholder specifically
    const sp = document.getElementById('toolSearch');
    if (sp) sp.placeholder = t('search-placeholder');
}

function toggleLang() {
    // Show/hide dropdown
    let dd = document.getElementById('langDropdown');
    if (!dd) {
        dd = document.createElement('div');
        dd.id = 'langDropdown';
        dd.className = 'lang-dropdown';
        dd.innerHTML = Object.entries(window.PDFStar_LANGS).map(([code, cfg]) =>
            `<button class="lang-item${code === _currentLang ? ' active' : ''}" onclick="selectLang('${code}')">${cfg.flag} ${cfg.name}</button>`
        ).join('');
        document.getElementById('langToggle').after(dd);
        setTimeout(() => document.addEventListener('click', closeLangDropdown, { once: true }), 100);
    } else {
        dd.remove();
    }
}

function selectLang(code) {
    applyLang(code);
    const dd = document.getElementById('langDropdown');
    if (dd) dd.remove();
}

function closeLangDropdown(e) {
    const dd = document.getElementById('langDropdown');
    if (dd && !dd.contains(e.target)) dd.remove();
}

// Init on load
document.addEventListener('DOMContentLoaded', () => applyLang(_currentLang));
